language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: "b44da38b783cb12476b6573ee85c33873a713df666d180dcb26eb8ad48c843b8"
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: CsYVKQ98qSvU/GcDwyMBySihtztWEolxQJcLbvKmieNqu6mYiIQE/LeEs7EbzTHoACwtR26zW/x46Qgrum36Jnr0SsXUi3bkjiMPM1qDE7DMZfZhepayELHoyPz64knDzMTtgRNE6K7gMSblg3Yv4aFl4Y4ZznLwNqhpQDV2fHZ3mOrf97CxWyPcKqs+RiHrHwdSzXlb3ZwoKA10zRRRI1QQc74sH5nn6HwG69bexKZR1TQNug6mSA9vkg4vSwylBdj8mKdSgpRqB0ZzMcrui6AjYOFlkkBrQY+z81w/79HgiJTwmHLsXgT72NzAGJQJ7ZVs40SS382J6BMTZYL0caDzSBdh30DCg71EV6l8jToaorCijFasI5MUVMy84JUoxc2i23vUjmBhRx27WZqaTL9Hpjg1xr5aUYNrH8Dsrf1sPySWa/ICuF8Chn23W+kgxND+J9Xfulcq2pzH0FCivyxQ0W6Tr/rpMYlR3UaLXNfuB2lKLPVoTltMtNFOo9sLEUH9ZaaQXSMcVfxo/5XTAzQSlhTQT7oPlqMQUoEJAEN+fRHAHYPFwa5YaTUf2ei6h7fL7NHRP3TDRZ87TMLdLC3a0JEb0jgu52+AUFZBJ4YmXsh9rRC8QRXxFFeimWYpmFZEdJB8OW6MlGaDla+EGeyiocjmuykiJWlDwAF4Rtw=
  on:
    tags: true
    branches: true
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
